### ISSUE TITLE
2.7: issue with latest RandomLib

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-math#1]
With RandomLib (and without mcrypt), running zend-form test suite:

`PHP Fatal error:  Class Zend\Math\Source\HashTiming contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (RandomLib\Source::isSupported) in /usr/share/php/Zend/Math/Source/HashTiming.php on line 111
`

---

Originally posted by @remicollet at https://github.com/zendframework/zend-math/issues/23

**Comment by weierophinney** [comment]
Notice also raised during zend-math test suite, see (Fedora QA)
https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-math?collection=f26


---

Originally posted by @remicollet at https://github.com/zendframework/zend-math/issues/23#issuecomment-247314882

**Comment by weierophinney** [comment]
@remicollet [ircmaxell/RandomLib](https://github.com/ircmaxell/RandomLib/blob/master/lib/RandomLib/Source.php) added the method `isSupported` to the interface `RandomLib\Source`. To fix this we need to merge #24 as new release 2.7.1. @weierophinney what do you think?


---

Originally posted by @ezimuel at https://github.com/zendframework/zend-math/issues/23#issuecomment-247335870

**Comment by weierophinney** [comment]
Let's wait and see if Anthony addresses the BC break, first; if so, we can potentially exclude that release from our supported versions list.


---

Originally posted by @weierophinney at https://github.com/zendframework/zend-math/issues/23#issuecomment-247338274

**Comment by weierophinney** [comment]
Anthony have answered on PR #24 


---

Originally posted by @remicollet at https://github.com/zendframework/zend-math/issues/23#issuecomment-247343395

**Comment by weierophinney** [comment]
Yep, I have same issue. Does anyone found hack for this fatal error?


---

Originally posted by @tasmaniski at https://github.com/zendframework/zend-math/issues/23#issuecomment-267313924

**Comment by weierophinney** [comment]
When will this be fixed?

---

Originally posted by @reinfi at https://github.com/zendframework/zend-math/issues/23#issuecomment-273758335

**Comment by samsonasik** [comment]
already fixed in 2.7.1 https://github.com/laminas/laminas-math/blob/8027b37e00accc43f28605c7d8fd081baed1f475/src/Source/HashTiming.php#L114-L117

I am closing it.
